language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - NO_GCE_CHECK=true
    - JAVA_HOME=/opt/ibm/java-x86_64-80
    - PATH=$PATH:$TRAVIS_BUILD_DIR/apache-cassandra-3.11.4/bin:${JAVA_HOME}/bin:/home/travis/build/${TRAVIS_REPO_SLUG}/scripts:/home/travis/build/EA/mdmx-ci-scripts:.
    #ibmsdk8 install fails unless we set PS1=">". See https://www-01.ibm.com/support/docview.wss?uid=swg21975406
    - PS1=">"
    #Space delimited emails of scrum team members to be notified about downstream builds. Downstream builds are builds triggered by an update in dependency"
    - TEAM_EMAILS="mkhatibi@ca.ibm.com,mwang@ca.ibm.com"
    - GIT_REPO_LC=$(echo $TRAVIS_REPO_SLUG | awk -F "/" '{print $2}' | tr '[:upper:]' '[:lower:]')
    - TAG_TYPE=`if [ "$TRAVIS_BRANCH" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then echo "latest"; else if [ "$TRAVIS_BRANCH" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then echo "pr"; else echo "$TRAVIS_BRANCH"; fi; fi;`
    - TAG=$TAG_TYPE-$TRAVIS_BUILD_NUMBER
    - TRAVISFVT=`if [ $(echo $TRAVIS_COMMIT_MESSAGE |  grep -ic travis-fvt) -gt 0 ] && [ $TRAVIS_BRANCH != "master" ];then echo yes; else echo no; fi`
    - tenantName=$(echo ${TRAVIS_BRANCH} | tr -cd 'a-zA-Z0-9' )
    - TENANT_NAME="${tenantName}${TRAVIS_BUILD_NUMBER}"
    - CASSANDRA_HOST=portal582-55.bmix-dal-yp-fdeeb3f8-024b-4f9f-a039-36d6afd4830b.2174223486.composedb.com
    - CASSANDRA_PORT=23006

    - PLATFORMIO_CI_SRC=esp8266/GSM_auto/GSM_auto.ino PLATFORMIO_CI_BOARDS_ARGS=--board=d1
    - PLATFORMIO_CI_SRC=esp8266/FM_RADIO/TEA5767_eeprom_i2c_lcdNokia5110_digitalvolume_3m3.ino PLATFORMIO_CI_BOARDS_ARGS=--board=d1



#before_install:
#    - echo "Script running before install"
#    - mkdir -p ~/.config/gh/
#    - pwd && ls -la
#    - cp -v -r .config/gh/config.yml ~/.config/gh/config.yml
#    - cd ~/.config/gh && ls -l 


install:
    - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
    - cd $TRAVIS_REPO_SLUG
    - git checkout -qf $TRAVIS_COMMIT
    - pip install -U platformio
    - platformio lib -g install "JsonStreamingParser" "ESP8266_SSD1306" "WifiManager@>=0.15.0-beta" "simpleDSTadjust" "Adafruit Unified Sensor" "DHT sensor library" "SRAM" "PubSubClient" "AWS-SDK-ESP" "WebSockets" "Paho"
    - platformio lib -g install "Adafruit GFX Library"
    - platformio lib update
    - wget https://github.com/cli/cli/releases/download/v0.5.7/gh_0.5.7_linux_amd64.tar.gz && tar -xzvf gh_0.5.7_linux_amd64.tar.gz
    - cp -v gh_0.5.7_linux_amd64/bin/gh ~/
    - ls -l /home/travis/


script:
   # - if [[ $PLATFORMIO_CI_BOARDS_ARGS ]]; then bash -c 'platformio ci --lib="." $PLATFORMIO_CI_BOARDS_ARGS'; else bash -c 'platformio ci --lib="." --board=esp32dev'; fi
    -  bash -c 'platformio ci --lib="." $PLATFORMIO_CI_BOARDS_ARGS'
   # -  bash -c 'cat file.log' 

after_success:
    - echo "SUCCESS"
    #- bash -c 'env'

after_failure:
    - echo "FAILURE"
    - cd $TRAVIS_BUILD_DIR
   # - cat /home/travis/.travis/functions
   # - pwd
   # - ls -l
    - chmod 777 create-github-issue.sh
    - ./create-github-issue.sh
#   - bash -c "env"
after_script:
    - echo "SCRIPT WAS ENDED"
