language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=esp8266/ESP8266_Web_Server_Arduino_IDE.ino PLATFORMIO_CI_BOARDS_ARGS=--board=d1



#before_install:
#    - echo "Script running before install"
#    - mkdir -p ~/.config/gh/
#    - pwd && ls -la
#    - cp -v -r .config/gh/config.yml ~/.config/gh/config.yml
#    - cd ~/.config/gh && ls -l 


install:
    - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
    - cd $TRAVIS_REPO_SLUG
    - git checkout -qf $TRAVIS_COMMIT
    - pip install -U platformio
    - platformio lib -g install "JsonStreamingParser" "ESP8266_SSD1306" "WifiManager@>=0.15.0-beta" "simpleDSTadjust" "Adafruit Unified Sensor" "DHT sensor library" "SRAM" "PubSubClient" "AWS-SDK-ESP" "WebSockets" "Paho"
    - platformio lib --storage-dir libraries/ install
    - platformio lib update
    - wget https://github.com/cli/cli/releases/download/v0.5.7/gh_0.5.7_linux_amd64.tar.gz && tar -xzvf gh_0.5.7_linux_amd64.tar.gz
    - cp -v gh_0.5.7_linux_amd64/bin/gh ~/
    - ls -l /home/travis/


script:
   # - if [[ $PLATFORMIO_CI_BOARDS_ARGS ]]; then bash -c 'platformio ci --lib="." $PLATFORMIO_CI_BOARDS_ARGS'; else bash -c 'platformio ci --lib="." --board=esp32dev'; fi
    -  bash -c 'platformio ci --lib="." $PLATFORMIO_CI_BOARDS_ARGS' 
    -  bash -c 'env' 

after_success:
    - echo "SUCCESS"
    - bash -c 'env'

after_failure:
    - echo "FAILURE"
    - cd $TRAVIS_BUILD_DIR
    - pwd
    - ls -l
    - chmod 777 create-github-issue.sh
    - ./create-github-issue.sh
#   - bash -c "env"
after_script:
    - echo "SCRIPT WAS ENDED"
